apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: attends-moi-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: attends-moi.local
